# Generated by Django 4.1 on 2023-05-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("activity_id", models.AutoField(primary_key=True, serialize=False)),
                ("activity_date", models.DateField()),
            ],
            options={
                "ordering": ["event", "activity_date", "entertainer"],
            },
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                ("album_id", models.AutoField(primary_key=True, serialize=False)),
                ("album_name", models.CharField(max_length=45)),
                ("released_date", models.DateField()),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={
                "ordering": ["album_name", "disambiguator"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="Create",
            fields=[
                ("create_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "ordering": ["role", "entertainer"],
            },
        ),
        migrations.CreateModel(
            name="Entertainer",
            fields=[
                ("entertainer_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("birth_date", models.DateField()),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "birth_date", "disambiguator"],
            },
        ),
        migrations.CreateModel(
            name="EntertainerType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "ordering": ["type_name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=45)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
            ],
            options={
                "ordering": ["event_name", "disambiguator"],
            },
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                ("event_cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "ordering": ["event_name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "ordering": ["role_name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("song_id", models.AutoField(primary_key=True, serialize=False)),
                ("song_name", models.CharField(max_length=45)),
                ("released_date", models.DateField()),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="song",
                        to="fandom.album",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="song",
                        to="fandom.company",
                    ),
                ),
            ],
            options={
                "ordering": ["song_name", "disambiguator", "released_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("event_name", "disambiguator"), name="unique_event"
            ),
        ),
        migrations.AddField(
            model_name="entertainer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entertainer",
                to="fandom.company",
            ),
        ),
        migrations.AddField(
            model_name="entertainer",
            name="entertainer_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entertainer",
                to="fandom.entertainertype",
            ),
        ),
        migrations.AddField(
            model_name="create",
            name="entertainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="create",
                to="fandom.entertainer",
            ),
        ),
        migrations.AddField(
            model_name="create",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="create",
                to="fandom.role",
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="album",
                to="fandom.company",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="entertainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity",
                to="fandom.entertainer",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity",
                to="fandom.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(
                fields=("song_name", "disambiguator", "album"), name="unique_song"
            ),
        ),
        migrations.AddConstraint(
            model_name="entertainer",
            constraint=models.UniqueConstraint(
                fields=("last_name", "first_name", "birth_date", "disambiguator"),
                name="unique_entertainer",
            ),
        ),
        migrations.AddConstraint(
            model_name="create",
            constraint=models.UniqueConstraint(
                fields=("role", "entertainer"), name="unique_create"
            ),
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                fields=("album_name", "released_date", "disambiguator"),
                name="unique_album",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.UniqueConstraint(
                fields=("event", "activity_date", "entertainer"), name="unique_activate"
            ),
        ),
    ]
