# Generated by Django 4.1 on 2023-05-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fandom", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EntertainerType",
            new_name="Style",
        ),
        migrations.AlterModelOptions(
            name="style",
            options={"ordering": ["style_name"]},
        ),
        migrations.RenameField(
            model_name="style",
            old_name="type_id",
            new_name="style_id",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="type_name",
            new_name="style_name",
        ),
        migrations.RemoveField(
            model_name="entertainer",
            name="entertainer_type",
        ),
        migrations.AddField(
            model_name="album",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="album",
                to="fandom.style",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="fandom.style",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="song",
                to="fandom.style",
            ),
        ),
        migrations.AlterField(
            model_name="entertainer",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entertainer",
                to="fandom.company",
            ),
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=45, unique=True)),
                (
                    "disambiguator",
                    models.CharField(blank=True, default="", max_length=45),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group",
                        to="fandom.company",
                    ),
                ),
            ],
            options={
                "ordering": ["group_name", "disambiguator"],
            },
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("group_name", "disambiguator"), name="unique_group"
            ),
        ),
    ]
