# Generated by Django 4.1 on 2023-05-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fandom", "0003_entertainergroup_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="create",
            options={"ordering": ["song", "role", "entertainer"]},
        ),
        migrations.RemoveConstraint(
            model_name="create",
            name="unique_create",
        ),
        migrations.AddField(
            model_name="create",
            name="song",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="create",
                to="fandom.song",
            ),
        ),
        migrations.AddConstraint(
            model_name="create",
            constraint=models.UniqueConstraint(
                fields=("song", "role", "entertainer"), name="unique_create"
            ),
        ),
    ]
