# Generated by Django 4.1 on 2023-05-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fandom", "0004_alter_create_options_remove_create_unique_create_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="create",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="create",
                to="fandom.song",
            ),
        ),
    ]
