# Generated by Django 4.1 on 2023-05-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fandom", "0005_alter_create_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activity",
                to="fandom.role",
            ),
        ),
    ]
