# Generated by Django 4.1 on 2023-05-05 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fandom", "0007_alter_activity_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventcategory",
            options={"ordering": ["event_cat_name"]},
        ),
        migrations.RenameField(
            model_name="eventcategory",
            old_name="event_name",
            new_name="event_cat_name",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="fandom.eventcategory",
            ),
        ),
    ]
