# Generated by Django 2.1.1 on 2018-11-13 20:48

from django.db import migrations

GROUPS = [
    {
        'name': 'admin',
    },
    {
        'name': 'lv3_user',
    },
    {
        'name': 'lv2_user',
    },
    {
        'name': 'lv1_user',
    },
    {
        'name': 'lv0_user',
    },
]


def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("fandom", "0008_alter_eventcategory_options_and_more"),
    ]

    operations = [

        migrations.RunPython(
            add_group_data,
            remove_group_data
        )

    ]
